export const mockListings = [
  {
    id: 1,
    title: 'Traditional Maasai Beaded Necklace',
    category: 'handicrafts',
    price: '150',
    location: 'Narok, Kenya',
    description: 'Authentic Maasai beaded necklace handmade by local artisans. Features traditional patterns and colors representing Maasai culture.',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400',
    verified: true,
  },
  {
    id: 2,
    title: 'Contemporary African Oil Painting',
    category: 'art',
    price: '800',
    location: 'Lagos, Nigeria',
    description: 'Vibrant oil painting depicting modern African urban life. Created by emerging Nigerian artist with unique perspective.',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400',
    verified: true,
  },
  {
    id: 3,
    title: 'Prime Nairobi Commercial Property',
    category: 'real-estate',
    price: '250000',
    location: 'Nairobi, Kenya',
    description: 'Strategic commercial property in Westlands, Nairobi CBD. High foot traffic area perfect for retail or office space.',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400',
    verified: false,
  },
  {
    id: 4,
    title: 'Handwoven Kente Cloth',
    category: 'handicrafts',
    price: '300',
    location: 'Accra, Ghana',
    description: 'Traditional Ghanaian Kente cloth handwoven using ancient techniques. Perfect for special occasions and ceremonies.',
    image: 'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=400',
    verified: true,
  },
  {
    id: 5,
    title: 'Abstract African Sculpture',
    category: 'art',
    price: '1200',
    location: 'Cape Town, South Africa',
    description: 'Contemporary bronze sculpture inspired by African wildlife and natural forms. One-of-a-kind piece by renowned sculptor.',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400',
    verified: false,
  },
  {
    id: 6,
    title: 'Beachfront Property - Zanzibar',
    category: 'real-estate',
    price: '180000',
    location: 'Zanzibar, Tanzania',
    description: 'Stunning beachfront villa with direct ocean access. Perfect for luxury vacation rental or personal retreat.',
    image: 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=400',
    verified: true,
  },
];
